version: '3.9'

services:
  datbase:
    image: postgres
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres

volumes:
   pgdata:
     driver: local